names:
- cereal
nc: 1
path: /home/mohamed/train/Small-Object-Detection-in-a-crowded-scene-using-YOLOv8/
test: cereal_dataset/yolo_dataset_random_tiles/test
train: cereal_dataset/yolo_dataset_random_tiles/train
val: cereal_dataset/yolo_dataset_random_tiles/valid
